### ISSUE TITLE
Recent commit "Added 7 missing worker tasks and reordered" incomplete?

### ISSUE THREAD

**Issue by yaalg** [d0sboots/perfect-tower#12]
I see the recent commit "Added 7 missing worker tasks and reordered", but it looks like there's still one missing: task.laboratory.gems.stack

Worker.LabTech0:17: bad argument #1 to worker.assignName

worker.assignName("task.laboratory.gems.stack", 0, "LabTech0")

It does work in-game (the script was exported from the game to your editor).

**Comment by d0sboots** [comment]
I actually did add it, but I misspelled the id. Thanks for the report, fixed now.
