### ISSUE TITLE
Auto-indent broken

### ISSUE THREAD

**Issue by Codrineye** [d0sboots/perfect-tower#13]
## Auto-indent always indents with spaces no matter what it's set to

the editor switched workspaces, reloaded and even tried in a new script but nothing permits indenting with tabs
![image](https://github.com/d0sboots/perfect-tower/assets/87333825/6c21aafa-e35a-4e8c-8c09-09bf359dc8bb)

**Comment by d0sboots** [comment]
It works for me just fine...

Press tab and enter. The next line will be indented. With the setting switched, it should be with a tab. (You can tell because it's a single char when you cursor left/right)

**Comment by Codrineye** [comment]
after reopening chrome, it worked well
